# netlify.toml

[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/robots.txt"
  to = "/public/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/public/sitemap.xml"
  status = 200
  force = true

