# netlify.toml

[build]
  publish = "."  # ton site est à la racine
  command = ""   # aucun build nécessaire pour un site HTML statique

[[plugins]]
  package = "netlify-plugin-sitemap"

  [plugins.inputs]
  prettyURLs = true
  exclude = ["/404.html"]

[[plugins]]
  package = "netlify-plugin-robots-txt"

  [plugins.inputs]
  policy = [
    { userAgent = "*", allow = "/" }
  ]
  sitemap = "https://vtc-majid.netlify.app/sitemap.xml"

